### ISSUE TITLE
InfringingUrl should only allow valid URLs

### ISSUE THREAD

**Issue by FrederikP** [xarf/schema-discussion#8]
Currently the InfringingUrl field in https://github.com/xarf/schema-discussion/blob/559b1520fee3f6da51340945a9f142c21347b08c/copyright.schema.json allows any string.

The sample even includes an invalid url (missing protocol http(s)://)

The format "url" does not exist in the json schema standard. It should be https://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3.5 .

**Comment by Qdulf** [comment]
Created pull request #9
